#!/usr/bin/env python3
"""
Identify videos that haven't been processed yet (no corresponding pkl file).

This script:
1. Scans video directory for all videos
2. Checks if corresponding pkl files exist
3. Generates a list/script to copy only unprocessed videos
4. Maintains directory structure for processing on another machine

Usage:
    # Generate list of unprocessed videos
    python identify_unprocessed_videos.py \
        --video_dir KArSL-502 \
        --pkl_dir data/karsl502-63kpts \
        --output_list unprocessed_videos.txt

    # Generate rsync script to copy them
    python identify_unprocessed_videos.py \
        --video_dir KArSL-502 \
        --pkl_dir data/karsl502-63kpts \
        --output_script copy_unprocessed.sh \
        --dest_machine user@hostname:/path/to/dest/
"""

import argparse
from pathlib import Path
from tqdm import tqdm


def find_unprocessed_videos(video_dir, pkl_dir):
    """
    Find all videos that don't have corresponding pkl files.
    
    Returns:
        list of (video_path, expected_pkl_path, relative_path) tuples
    """
    video_path = Path(video_dir)
    pkl_path = Path(pkl_dir)
    
    # Get all user directories
    user_dirs = sorted([d for d in video_path.iterdir() 
                        if d.is_dir() and d.name.startswith('user')])
    
    print(f"Scanning {len(user_dirs)} user directories...")
    
    unprocessed = []
    processed_count = 0
    
    for user_dir in tqdm(user_dirs, desc="Checking videos"):
        user_name = user_dir.name
        
        # Get all gesture directories
        gesture_dirs = sorted([d for d in user_dir.iterdir() 
                              if d.is_dir() and d.name.startswith('G')])
        
        for gesture_dir in gesture_dirs:
            gesture_name = gesture_dir.name
            
            # Get all video files
            video_files = list(gesture_dir.glob('*.mp4')) + list(gesture_dir.glob('*.avi'))
            
            for video_file in video_files:
                # Construct expected pkl path
                pkl_filename = f"{user_name}_{gesture_name}_{video_file.stem}.pkl"
                expected_pkl = pkl_path / "all" / gesture_name / pkl_filename
                
                # Check if pkl exists
                if expected_pkl.exists():
                    processed_count += 1
                else:
                    # Store relative path for easier copying
                    rel_path = video_file.relative_to(video_path)
                    unprocessed.append((str(video_file), str(expected_pkl), str(rel_path)))
    
    print(f"\nSummary:")
    print(f"  Total processed: {processed_count}")
    print(f"  Total unprocessed: {len(unprocessed)}")
    
    return unprocessed


def write_file_list(unprocessed, output_file):
    """Write list of unprocessed videos to a text file."""
    with open(output_file, 'w') as f:
        for video_path, pkl_path, rel_path in unprocessed:
            f.write(f"{video_path}\n")
    
    print(f"\n✓ Wrote {len(unprocessed)} unprocessed video paths to: {output_file}")


def write_rsync_script(unprocessed, video_dir, output_script, dest_base):
    """
    Generate rsync script to copy unprocessed videos maintaining directory structure.
    """
    video_path = Path(video_dir)
    
    with open(output_script, 'w') as f:
        f.write("#!/bin/bash\n")
        f.write("# Rsync script to copy unprocessed videos\n")
        f.write("# Generated by identify_unprocessed_videos.py\n\n")
        f.write(f"SOURCE_DIR=\"{video_path}\"\n")
        f.write(f"DEST=\"{dest_base}\"\n\n")
        f.write("echo \"Copying unprocessed videos...\"\n")
        f.write("echo \"Source: $SOURCE_DIR\"\n")
        f.write("echo \"Destination: $DEST\"\n")
        f.write(f"echo \"Total files: {len(unprocessed)}\"\n")
        f.write("echo \"\"\n\n")
        
        # Group by user for better organization
        user_videos = {}
        for video_path_str, pkl_path, rel_path in unprocessed:
            user = Path(rel_path).parts[0]
            if user not in user_videos:
                user_videos[user] = []
            user_videos[user].append(rel_path)
        
        # Write rsync commands per user
        for user, videos in sorted(user_videos.items()):
            f.write(f"# {user}: {len(videos)} videos\n")
            f.write(f"echo \"Copying {user}...\"\n")
            
            # Create a file list for this user
            user_list_file = f"unprocessed_{user}.txt"
            f.write(f"cat > {user_list_file} << 'EOF'\n")
            for rel_path in videos:
                f.write(f"{rel_path}\n")
            f.write("EOF\n\n")
            
            # Rsync using the file list
            f.write(f"rsync -av --files-from={user_list_file} \"$SOURCE_DIR/\" \"$DEST/\"\n")
            f.write(f"rm {user_list_file}\n\n")
        
        f.write("echo \"\"\n")
        f.write("echo \"✓ Copy complete!\"\n")
        f.write(f"echo \"Total videos copied: {len(unprocessed)}\"\n")
    
    # Make script executable
    Path(output_script).chmod(0o755)
    
    print(f"\n✓ Generated rsync script: {output_script}")
    print(f"  Run it with: ./{output_script}")


def write_manual_copy_script(unprocessed, video_dir, output_script):
    """
    Generate a simple copy script (for local copying without rsync).
    """
    video_path = Path(video_dir)
    
    with open(output_script, 'w') as f:
        f.write("#!/bin/bash\n")
        f.write("# Script to copy unprocessed videos\n")
        f.write("# Usage: ./script.sh /destination/path\n\n")
        f.write("if [ $# -eq 0 ]; then\n")
        f.write("    echo \"Error: Please provide destination directory\"\n")
        f.write("    echo \"Usage: $0 /destination/path\"\n")
        f.write("    exit 1\n")
        f.write("fi\n\n")
        f.write("DEST=\"$1\"\n")
        f.write(f"SOURCE=\"{video_path}\"\n\n")
        f.write(f"echo \"Copying {len(unprocessed)} unprocessed videos...\"\n")
        f.write("echo \"Source: $SOURCE\"\n")
        f.write("echo \"Destination: $DEST\"\n")
        f.write("echo \"\"\n\n")
        
        for i, (video_path_str, pkl_path, rel_path) in enumerate(unprocessed, 1):
            # Create directory structure
            dir_path = str(Path(rel_path).parent)
            f.write(f"# {i}/{len(unprocessed)}: {rel_path}\n")
            f.write(f"mkdir -p \"$DEST/{dir_path}\"\n")
            f.write(f"cp \"$SOURCE/{rel_path}\" \"$DEST/{rel_path}\"\n")
            
            # Progress indicator every 100 files
            if i % 100 == 0:
                f.write(f"echo \"Progress: {i}/{len(unprocessed)}\"\n")
            f.write("\n")
        
        f.write("echo \"\"\n")
        f.write("echo \"✓ Copy complete!\"\n")
    
    Path(output_script).chmod(0o755)
    print(f"\n✓ Generated copy script: {output_script}")
    print(f"  Run it with: ./{output_script} /destination/path")


def main():
    parser = argparse.ArgumentParser(
        description="Identify unprocessed videos for resuming on another machine"
    )
    parser.add_argument(
        "--video_dir",
        type=str,
        required=True,
        help="Directory containing videos (e.g., KArSL-502)"
    )
    parser.add_argument(
        "--pkl_dir",
        type=str,
        required=True,
        help="Directory containing pkl files (e.g., data/karsl502-63kpts)"
    )
    parser.add_argument(
        "--output_list",
        type=str,
        help="Output file for list of unprocessed videos"
    )
    parser.add_argument(
        "--output_script",
        type=str,
        help="Output shell script for copying unprocessed videos"
    )
    parser.add_argument(
        "--dest_machine",
        type=str,
        help="Destination for rsync (e.g., user@host:/path/). If not provided, generates local copy script."
    )
    
    args = parser.parse_args()
    
    if not args.output_list and not args.output_script:
        print("Error: Specify at least --output_list or --output_script")
        return
    
    print("=" * 80)
    print("Identifying Unprocessed Videos")
    print("=" * 80)
    print(f"Video directory: {args.video_dir}")
    print(f"PKL directory:   {args.pkl_dir}")
    print("=" * 80)
    print()
    
    # Find unprocessed videos
    unprocessed = find_unprocessed_videos(args.video_dir, args.pkl_dir)
    
    if len(unprocessed) == 0:
        print("\n✓ All videos have been processed!")
        return
    
    # Write outputs
    if args.output_list:
        write_file_list(unprocessed, args.output_list)
    
    if args.output_script:
        if args.dest_machine:
            write_rsync_script(unprocessed, args.video_dir, args.output_script, args.dest_machine)
        else:
            write_manual_copy_script(unprocessed, args.video_dir, args.output_script)
    
    print("\n" + "=" * 80)
    print("Next steps:")
    print("=" * 80)
    print("1. Copy unprocessed videos to other machine using generated script")
    print("2. On other machine, run:")
    print("   python extract_63_keypoints_mp.py \\")
    print(f"       --input_dir {Path(args.video_dir).name} \\")
    print("       --output_dir data/karsl502-63kpts/ \\")
    print("       --num_workers 4")
    print("3. Copy generated pkl files back:")
    print("   rsync -av other_machine:/path/to/data/karsl502-63kpts/ data/karsl502-63kpts/")
    print("=" * 80)


if __name__ == "__main__":
    main()
